version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8888:8000
    environment:
      - DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}"
    depends_on:
      - db
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
  db:
    image: postgres:15.2-bullseye
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
volumes:
  postgres_data:
