"""update_table

Revision ID: 27a1953753e0
Revises: d58f01f038e1
Create Date: 2023-04-06 14:41:25.580101

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '27a1953753e0'
down_revision = 'd58f01f038e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_type',
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'desc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.PrimaryKeyConstraint('name')
                    )
    op.create_table('hardware',
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('short_description',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('full_description',
                              sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['type'], ['hardware_type.name'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('modified_at', sa.DateTime(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('total', sa.Float(), nullable=False),
                    sa.Column('shipment_deadline', sa.Date(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('HardwareOrder',
                    sa.Column(
                        'hardware_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['hardware_id'], ['hardware.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('hardware_id', 'order_id')
                    )
    op.create_table('contracts',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('order_id', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=False),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('status_changes',
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column(
                        'id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'orders_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('manager_id', sqlmodel.sql.sqltypes.AutoString(),
                              nullable=True),
                    sa.ForeignKeyConstraint(
                        ['manager_id'], ['manager.user_id'], ),
                    sa.ForeignKeyConstraint(['orders_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_changes')
    op.drop_table('contracts')
    op.drop_table('HardwareOrder')
    op.drop_table('orders')
    op.drop_table('hardware')
    op.drop_table('hardware_type')
    # ### end Alembic commands ###
