"""delete_contracts

Revision ID: 47f34b0167ec
Revises: c4cfd1b812e0
Create Date: 2023-04-12 09:47:03.458967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47f34b0167ec'
down_revision = 'c4cfd1b812e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='contracts_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='contracts_pkey')
    )
    # ### end Alembic commands ###
