"""update_hardware_order_table

Revision ID: c22ba7270357
Revises: 27a1953753e0
Create Date: 2023-04-07 19:29:59.390236

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c22ba7270357'
down_revision = '27a1953753e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_order',
                    sa.Column(
                        'hardware_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column(
                        'order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('volume', sa.Integer(), nullable=False),
                    sa.Column('value', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['hardware_id'], ['hardware.id'], ),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
                    sa.PrimaryKeyConstraint('hardware_id', 'order_id')
                    )
    op.drop_table('HardwareOrder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HardwareOrder',
                    sa.Column('hardware_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.Column('order_id', sa.VARCHAR(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['hardware_id'], ['hardware.id'], name='HardwareOrder_hardware_id_fkey'),
                    sa.ForeignKeyConstraint(
                        ['order_id'], ['orders.id'], name='HardwareOrder_order_id_fkey'),
                    sa.PrimaryKeyConstraint('hardware_id', 'order_id',
                                            name='HardwareOrder_pkey')
                    )
    op.drop_table('hardware_order')
    # ### end Alembic commands ###
