"""update_status_changes_table

Revision ID: c4cfd1b812e0
Revises: c22ba7270357
Create Date: 2023-04-07 23:37:24.561482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4cfd1b812e0'
down_revision = 'c22ba7270357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('status_changes_manager_id_fkey',
                       'status_changes', type_='foreignkey')
    op.drop_column('status_changes', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status_changes', sa.Column(
        'manager_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('status_changes_manager_id_fkey',
                          'status_changes', 'manager', ['manager_id'], ['user_id'])
    # ### end Alembic commands ###
